version: "3.9"

services:
  frontend:
    build: ./svch
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api/
      - WDS_SOCKET_PORT=0
    depends_on:
      - server
    stdin_open: true
    tty: true
    volumes:
      - ./svch:/app
    command: npm start

  server:
    build: ./server
    container_name: server
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=1d2i3m4a5DIMAS
      - DB_NAME=AutoSport
      - NODE_ENV=development
      - PORT=5000
    depends_on:
      - db
    volumes:
      - ./server:/server
      - /server/node_modules
    command: node server.js

  db:
    image: postgres:17
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1d2i3m4a5DIMAS
      POSTGRES_DB: AutoSport
    ports:
      - "5432:5432"
    user: root
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d

volumes:
  db_data:
